flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- QuickCheck-2.10.0.1
- StateVar-1.1.0.4
- attoparsec-0.13.2.0
- blaze-builder-0.4.0.2
- brick-0.24
- contravariant-1.4
- data-clist-0.1.2.0
- dlist-0.8.0.3
- hashable-1.2.6.1
- ini-0.3.5
- integer-logarithms-1.0.2
- microlens-0.4.8.1
- microlens-mtl-0.1.11.0
- microlens-th-0.4.1.1
- mtl-2.2.1
- parallel-3.2.1.1
- parsec-3.1.11
- primitive-0.6.2.0
- random-1.1
- scientific-0.3.5.1
- semigroups-0.18.3
- stm-2.4.4.1
- split-0.2.3.2
- terminal-size-0.3.2.1
- text-1.2.2.2
- text-zipper-0.10
- tf-random-0.5
- transformers-compat-0.5.1.4
- unordered-containers-0.2.8.0
- utf8-string-1.0.1.1
- vector-0.12.0.1
- void-0.7.2
- vty-5.17
- word-wrap-0.4.1
- xdg-basedir-0.2.2
resolver: ghc-8.0.2
