on: push

jobs:
 stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        stack: ["2.3.1"]
        ghc: ["8.8.3"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1.1.4
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build Dependencies
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --system-ghc

    - name: Install
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --copy-bins
        mkdir caligraph-bin
        cp -r `stack path --local-bin`/* caligraph-bin/

    - uses: actions/upload-artifact@v2
      with:
        name: Save binaries
        path: caligraph-bin
