on: push

jobs:
  build:
    name: Build and test with stack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.8'
          enable-stack: true
          stack-version: 'latest'
      - name: Run tests
        run: stack test
