on: push

jobs:
 stack:
    name: stack / ghc ${{ matrix.ghc }} on ${{ matrix.os }}
    strategy:
      matrix:
        stack: ["2.3.1"]
        ghc: ["8.8.3"]
        os: [ubuntu-22.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1.1.4
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ matrix.ghc }}-stack

    - name: Build Dependencies
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --system-ghc

    - name: Install
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --copy-bins
        mkdir -p caligraph-bin/
        cp -r `stack path --local-bin`/* caligraph-bin/

    - uses: actions/upload-artifact@v4
      with:
        name: Binaries ${{ matrix.os }}
        path: caligraph-bin
